---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/manifests/traefik
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: ingress
