apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service
  namespace: ingress

spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: dashboard
  selector:
    app: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-service
  namespace: ingress
  annotations:
    load-balancer.hetzner.cloud/location: hel1
    load-balancer.hetzner.cloud/ipv6-disabled: true
    load-balancer.hetzner.cloud/protocol: tcp

spec:
  type: LoadBalancer
  ports:
    - targetPort: web
      port: 80
  selector:
    app: traefik
